<?php
include_once "security.php";

?>
<html>
<head>
<title>Create an XML Article</title>
</head>
<body>
<h1>Create an XML Article</h1>

<a href="articletool.php">Cancel</a><br>
<br>
<form action="addArticle.php" method="post">
  <table border=1 cellspacing=0 cellpadding=3>
    <tr valign=top> 
      <td width="135">Article ID</td>
      <td width="634"> autogenerated<font size="-1">&nbsp;</font></td>
    </tr>
    <tr valign=top> 
      <td>Status</td>
      <td><select name="status">
          <option value="in progress">In progress</option>
          <option value="live">Live</option>
          <option value="Expired">Expired</option>
        </select></td>
    </tr>
    <tr valign=top> 
      <td>Headline</td>
      <td> <input name="headline" type="text" id="headline" size="60"></td>
    </tr>
    <tr valign=top> 
      <td>Author</td>
      <td> <select name="authorID" id="authorID">
          <?php
	$aList = simplexml_load_file("../xml/authors.xml");
	foreach ($aList->xpath("author") as $author){
		echo "<option value='". $author['id']."'>". $author->name."</option>\n";
	}
	?>
        </select>
		</td>
    </tr>
    <tr valign=top> 
      <td>Category</td>
      <td><select name="categoryID" id="categoryID">
          <?php
	$categoryList = simplexml_load_file("../xml/category.xml");
	foreach ($categoryList->xpath("item[@status='live']") as $cat){
		echo "<option value='". $cat['id']."'>". $cat['label']."</option>\n";
	}
	?>
        </select></td>
    </tr>
    <tr valign=top>
      <td>Expiration Date</td>
      <td><input name="expireDate" type="text" id="expireDate">
        (2004-01-01)</td>
    </tr>
    <tr valign=top> 
      <td>Keywords</td>
      <td> <p> 
          <input name="keywords" type="text" id="keywords" size="50">
          <font size="-1"><br>
          </font><font size="-1">(separate keywords with commas)</font> </p></td>
    </tr>
    <tr valign=top> 
      <td>Abstract</td>
      <td><textarea name="abstract" cols="50" rows="5" id="abstract"></textarea></td>
    </tr>
    <tr valign=top> 
      <td> <p>Article Body<br>
        </p></td>
      <td> <p>Copy and paste HTML:</p>
        <p> 
          <textarea name="body" cols="70" rows="10" wrap="soft" id="body"></textarea>
        </p>
        <p>&nbsp; </p></td>
    </tr>
    <tr valign=top> 
      <td colspan=2> <div align="center"> 
		  <input name="pubDate" type="hidden" value="<?php echo date("Y-m-d");?>">
          <input type="submit" name="Add Article" value="Add Article">
          &nbsp; 
          <input name="reset" type="reset" id="reset" value="Reset">
        </div></td>
    </tr>
  </table>
</form>
</body></html>
