<?php
include_once "security.php";

?>
<html>
<head>
<title>Create an XML News Item</title>
</head>
<body>
<h1>Create an XML News Item</h1>

<a href="newstool.php">Cancel</a><br>
<br>
<form action="addNews.php" method="post">
  <table border=1 cellspacing=0 cellpadding=3>
    <tr valign=top> 
      <td width="135">News ID</td>
      <td width="634">autogenerated</td>
    </tr>
    <tr valign=top> 
      <td>Status</td>
      <td><select name="status">
          <option value="in progress">In progress</option>
          <option value="live">Live</option>
          <option value="Expired">Expired</option>
        </select></td>
    </tr>
    <tr valign=top> 
      <td>Headline</td>
      <td> <input name="headline" type="text" id="headline" size="60"></td>
    </tr>
    <tr valign=top> 
      <td>Author</td>
      <td> <select name="authorid" id="authorid">
          <?php
	$aList = simplexml_load_file("../xml/authors.xml");
	foreach ($aList->xpath("author") as $author){
		echo "<option value='". $author['id']."'>". $author->name."</option>\n";
	}
	?>
        </select></td>
    </tr>
    <tr valign=top> 
      <td>Category</td>
      <td><select name="categoryid" id="categoryid">
          <?php
	$categoryList = simplexml_load_file("../xml/category.xml");
	foreach ($categoryList->xpath("item[@status='live']") as $cat){
		echo "<option value='". $cat['id']."'>". $cat['label']."</option>\n";
	}
	?>
        </select></td>
    </tr>
    <tr valign=top> 
      <td>Expiration Date</td>
      <td><input name="expiredate" type="text" id="expiredate">
        (2004-01-01)</td>
    </tr>
    <tr valign=top> 
      <td>URL</td>
      <td><input name="url" type="text" id="url" size="50"></td>
    </tr>
    <tr valign=top> 
      <td>Keywords</td>
      <td> <p> 
          <input name="keywords" type="text" id="keywords" size="50">
          <font size="-1"><br>
          </font><font size="-1">(separate keywords with commas)</font> </p></td>
    </tr>
    <tr valign=top> 
      <td>Description</td>
      <td><textarea name="description" cols="50" rows="5" id="description"></textarea></td>
    </tr>
    <tr valign=top> 
      <td colspan=2> <div align="center"> 
		  <input name="pubdate" type="hidden" value="<?php echo date("Y-m-d");?>">
          <input name="Add News" type="submit" id="Add News" value="Add News Item">
          &nbsp; 
          <input name="reset" type="reset" id="reset" value="Reset">
        </div></td>
    </tr>
  </table>
</form>
</body></html>
