<?php
include_once "security.php";

?>
<html>
<head>
<title>Create Web Copy</title>
</head>
<body>
<h1>Create Web Copy</h1>

<a href="webcopytool.php">Cancel</a><br>
<br>
<form action="addCopy.php" method="post">
  <table border=1 cellspacing=0 cellpadding=3>
    <tr valign=top> 
      <td width="135">Web Copy ID</td>
      <td width="634"> autogenerated<font size="-1">&nbsp;</font></td>
    </tr>
    <tr valign=top> 
      <td>Status</td>
      <td><select name="status">
          <option value="in progress">In progress</option>
          <option value="live">Live</option>
          <option value="Expired">Expired</option>
        </select></td>
    </tr>
    <tr valign=top> 
      <td>Headline</td>
      <td> <input name="headline" type="text" id="headline" size="60"></td>
    </tr>
    <tr valign=top> 
      <td>Navigation Label</td>
      <td> <input name="navlabel" type="text" id="navlabel" size="60"></td>
    </tr>
    <tr valign=top> 
      <td>Description</td>
      <td><textarea name="description" cols="50" rows="5" id="abstract"></textarea></td>
    </tr>
    <tr valign=top> 
      <td> <p>Body<br>
        </p></td>
      <td> <p>Copy and paste HTML:</p>
        <p> 
          <textarea name="body" cols="70" rows="10" wrap="soft" id="body"></textarea>
        </p>
        <p>&nbsp; </p></td>
    </tr>
    <tr valign=top> 
      <td colspan=2> <div align="center"> 
		  <input name="pubDate" type="hidden" value="<?php echo date("Y-m-d");?>">
          <input type="submit" name="Add Web Copy" value="Add Web Copy">
          &nbsp; 
          <input name="reset" type="reset" id="reset" value="Reset">
        </div></td>
    </tr>
  </table>
</form>
</body></html>
